#define MAX_SYMBOL_LENGTH 51//17
#define MAX_SVALUE_LENGTH 5
#define MAX_COMP_LENGTH 4
#define MAX_COMP_COUNT 28
#define MAX_CVALUE_LENGTH 8
#define MAX_DJ_LENGTH 5
#define MAX_DJ_COUNT 8
#define MAX_DJVALUE_LENGTH 4
#define TAB_LENGTH 8
#define INSTRUCT_WIDTH 16
#define MAX_LINE_LENGTH 81
#define SYMBOL_TABLE_NAME "s_table.dat"
#define COMP_TABLE_NAME "c_table.dat"
#define DJ_TABLE_NAME "dj_table.dat"
